name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - uses: MilesChou/composer-action@master
      with:
        args: install
    - run: composer install
    - run: npm install
    - run: npm run build --if-present
    - uses: actions/upload-artifact@v2
      with: 
        name: 'release'
        path: './build/'